[project]
name = "backend"
version = "0.1.0"
description = "Backend for Chronotopic"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.4",
    "sqlalchemy>=2.0.36",
    "uvicorn>=0.32.0",
]
